Fixed models for new data format
smarturban/sstu_schedule pull request #3
Opened 2017-02-21 18:13 UTC by vovcyan

2017-02-26 19:50 UTC, SevakAvet requested changes

2017-02-26 19:50 UTC, SevakAvet commented on src/main/java/com/ssu/schedule/parser/ParserSSU.java
> +        ArrayList<Lesson> lessons = new ArrayList<>();
List<Lesson> lessons = ...

2017-02-26 19:50 UTC, SevakAvet commented on src/main/java/com/ssu/schedule/parser/ParserSSU.java
> +            }
switch with one case?

2017-02-26 19:50 UTC, SevakAvet commented on src/main/java/com/ssu/schedule/parser/ParserSSU.java
> +        OkHttpClient client = new OkHttpClient();
you don't need to create client and requestBuilder for each request, create two beans instead and inject (@autowire) them whenever they're used

2017-02-26 19:50 UTC, SevakAvet commented on src/main/java/com/ssu/schedule/web/rest/ScheduleController.java
> +            Gson gson = new GsonBuilder().create();
The same as for okhttpclient (see comment above), create bean

2017-02-27 08:26 UTC, merged

2017-02-27 14:11 UTC, vovcyan commented on src/main/java/com/ssu/schedule/web/rest/ScheduleController.java
> +            Gson gson = new GsonBuilder().create();
Ok

2017-02-27 14:11 UTC, vovcyan commented on src/main/java/com/ssu/schedule/parser/ParserSSU.java
> +        OkHttpClient client = new OkHttpClient();
Ok

2017-02-27 14:11 UTC, vovcyan commented on src/main/java/com/ssu/schedule/parser/ParserSSU.java
> +        ArrayList<Lesson> lessons = new ArrayList<>();
Ok

2017-02-27 14:13 UTC, vovcyan commented on src/main/java/com/ssu/schedule/parser/ParserSSU.java
> +            }
Ok